### ISSUE TITLE
Changs to all factories and instances

### ISSUE THREAD

**Issue by EGreg** [Intercoin/ReleaseManager#13]
Just change `FactoryBase` in all repos. In this way, factories will have these changes.

1. Right now we use `[create](https://github.com/Intercoin/NonFungibleTokenContract/blob/main/contracts/FactoryBase.sol#L44)` in factories `produce()` methods. But I would like to ask to [use `create2` instead](https://leftasexercise.com/2021/09/05/a-deep-dive-into-solidity-contract-creation-and-the-init-code/), and to take the `salt` parameter as the first parameter in `produce` (first because we may add more parameters in the future).

The ITR token deployer address will deploy ITR so it can be the exact same token address on BSC as on ETH. But that's an exception. In general, people should be able to create instances with vanity addresses. But we may want to charge them for it.

3. Rename `factory` to `deployer` in every instance that has `overrideCostManager`. If instance was deployed manually, whoever called initialize() is the "deployer". Otherwise it is the factory. Since each of our smart contracts has an ICostManager, and overrideCostManager, then please store `deployer`. (It would also help you to find out who deployed the contract and when).

4. Make sure all factories implement the Ownable interface. Just use OpenZeppelin's implementation. You'll transfer ownership of the factory to our Intercoin ControlContract instance once they're all deployed. It will probably have a vanity address (see #3).
 
5. Make sure all factories implement the `ICostManager` interface. And copy what `_accountForOperation` does, sending. The owners of the factory can always change the cost manager at any time, affecting its ability to `produce` contracts. But if they renounce ownership, whatever is there remains there.

**Comment by artman325** [comment]
> 5. Make sure all factories implement the ICostManager interface. And copy what _accountForOperation does, sending. The owners of the factory can always change the cost manager at any time, affecting its ability to produce contracts. But if they renounce ownership, whatever is there remains there.

there are no sense if factory will implement `ICostManager` interface. factory can produce instance and that's all. but Implementation will do mote things. and operation produce can be trigerred in initialize method

**Comment by artman325** [comment]
> 4. Make sure all factories implement the Ownable interface. Just use OpenZeppelin's implementation. You'll transfer ownership of the factory to our Intercoin ControlContract instance once they're all deployed. It will probably have a vanity address (see https://github.com/Intercoin/ReleaseManager/pull/3).

all intercoin factories will implement ReleaseManagerHelper which contains Ownable interface. And need only for calling `registerReleaseManager`  when producing instances in time interval after initialize but before transferOwnership to sender. That's all. Any other methods does not require `onlyOwner` modifier.

**Comment by EGreg** [comment]
@artman325 but how will factories charge users a token for

**Comment by artman325** [comment]
3. just revert all changes. means deployer should be 'factory'
Also need to remove this section
`(deployer.isContract()) `
We will not check way when initialization contract happens by user


All thing that was left . it's no need to do
