### ISSUE TITLE
replace old when newRelease call

### ISSUE THREAD

**Issue by artman325** [Intercoin/ReleaseManager#9]
need to replace old factory when user call `newRelease` with the same `tagname` and `factoryIndex`
the goal to return the only one and last by tag

**Comment by EGreg** [comment]
To do this, you will need to have an additional mapping `releases`. Use a mapping like this:

```
releases[tag][index] = address
```

Update this mapping. You can read `releases` and delete from `factories[oldAddress]` mapping to save some gas.
